#!/bin/sh
# Runs the tester application, optionally using the provided Python version.
# ./runtester [3|2]

if [ -n $1 ] && [ "$1" = "2" ]; then
	echo gcoap tester on Python2
	python tester.py
else
	echo gcoap tester on Python3
	python3 tester.py
fi
