#!/bin/sh
# Runs the gcoap tester application, optionally using the provided Python
# version and IP port. Python version defaults to 3. Tester listens on all
# network interfaces.
#
# Need to set PYTHONPATH in a development environment.
#
# PYTHONPATH="../../soscoap/repo:../repo" ./runtester [-v 2] [-p port]

python_exe="python3"
if [ -n $2 ] && [ "$1" = "-v" ] && [ "$2" = "2" ]; then
    python_exe="python2"
    shift
    shift
fi

port="5683"
if [ -n $2 ] && [ "$1" = "-p" ]; then
    port=$2
fi

echo gcoap tester on $python_exe, port $port
$python_exe -m gcoaptest.tester -p $port
